### ISSUE TITLE
batch_size and trainning time

### ISSUE THREAD

**Issue by cv-lab-x** [autonomousvision/monosdf#24]
hi, thanks for your great work!
1. why you use batch_size = 1 in your code, did your try to imcrease batch_size ? i got some errors when i just increaset batch_size from 1 to 2.
2. can this codes run with multi-gpu to improve training time?
3. what params can i try to improve the quality of the sdf and psnr?

looking forward to your reply! thanks! @niujinshuchong

**Comment by niujinshuchong** [comment]
Hi,
1. Because we need to align rendered depth with monocular depth so they should come from the same image. I think use more images at a time is also possible but you need to adapt the code to align them separately.
2. Yes, using multi-gpu will converge faster.
3.  You can use grids representation to get better psnr and more detailed sdf but the sdf might be noise.
